"""add_contact_opt_out_fields

Revision ID: 8e6aaad579e1
Revises: g2h3i4j5k6l7
Create Date: 2026-07-11 14:52:47.328278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e6aaad579e1'
down_revision: Union[str, Sequence[str], None] = 'g2h3i4j5k6l7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('is_opted_out', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('contacts', sa.Column('opted_out_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contacts', 'opted_out_at')
    op.drop_column('contacts', 'is_opted_out')
    # ### end Alembic commands ###
